apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app  
  namespace: default  

spec:
  project: my-project 

  source:
    repoURL: https://github.com/chedicoder/project 
    targetRevision: main  
    path: my-charts

  destination:
    server: https://kubernetes.default.svc   
    namespace: argocd 
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  

    automated:
      selfHeal: true  
      prune: true